server:
  # SpringBoot 项目的运行端口即为客户端反向 Websocket 连接端口
  port: 5555
  # 反向WS设置
  ws-reverse:
    # 反向WS Universal 地址
    # 注意 设置了此项地址后下面两项将会被忽略
    universal: ws://127.0.0.1:5555/ws/shiro
    # 反向WS API 地址
    api: ws://your_websocket_api.server
    # 反向WS Event 地址
    event: ws://your_websocket_event.server
    # 重连间隔 单位毫秒
    reconnect-interval: 3000
#    middlewares:
#      <<: *default # 引用默认中间件

spring:
  profiles.active: prod

shiro:
  ws-config:
    # 反向 Websocket 连接地址，无需该配置字段可删除，将使用默认值 "/ws/shiro"
    ws-url: "/ws/shiro"
    # 访问密钥，强烈推荐在公网的服务器设置
    access-token: ""
    # 超时回收，默认10秒
    timeout: 10
    # 二进制消息的最大长度
    max-binary-message-buffer-size: 512000
    # 最大空闲时间，超过这个时间将关闭会话
    max-session-idle-timeout: 900000
    # 最大文本消息缓冲区
    max-text-message-buffer-size: 512000
